### ISSUE TITLE
Tautan riwayat halaman

### ISSUE THREAD

**Issue by herpiko** [BlankOn/wiki#102]
Misal, halaman https://github.com/BlankOn/wiki/blob/master/TimPengembang/Infrastruktur/RepositoriPengembangan.md, selain punya tombol `sunting`, punya tombol `riwayat`, mengacu ke halaman komit, yaitu https://github.com/BlankOn/wiki/commits/master/TimPengembang/Infrastruktur/RepositoriPengembangan.md

**Comment by samsulmaarif** [comment]
Wah, halaman yang tersebut termasuk halaman yang belum sempat saya rapihkan :v: :pray: :pray:

**Comment by herpiko** [comment]
Dipindahkan ke https://github.com/BlankOn/Verbeek/issues/72
