### ISSUE TITLE
Judul halaman ditampilkan sebagai README di navigasi bawah

### ISSUE THREAD

**Issue by artemtech** [BlankOn/wiki#120]
Saat ini tampilan judul di navigasi bawah ada yang menampilkan judul artikelnya tapi juga ada yang masih berupa README.
contoh:
![gambar1](https://user-images.githubusercontent.com/22854966/97802274-d6c5bf80-1c74-11eb-8da6-f364fe4d1dfc.png)
![gambar2](https://user-images.githubusercontent.com/22854966/97802315-286e4a00-1c75-11eb-8edb-c7bfbb865429.png)

**Comment by FaiqAminuddin** [comment]
minta tolong pak @kudaliar032

**Comment by kudaliar032** [comment]
Issue ini sudah saya perbaiki pada pull request berikut https://github.com/BlankOn/wiki/pull/140, silahkan di cek kembali :pray: cc: @artemtech @FaiqAminuddin

**Comment by artemtech** [comment]
dari saya sih udah ok pak @kudaliar032 
sudah tidak ada navigasi yang README di tombol next/previous

**Comment by FaiqAminuddin** [comment]
@artemtech Sudah ok. Terima kasih
