### ISSUE TITLE
halaman istilah beserta penjelasannya

### ISSUE THREAD

**Issue by FaiqAminuddin** [BlankOn/wiki#29]
Apakah wiki BlankOn juga perlu dilengkapi dengan halaman istilah-istilah umum tik seperti unduh, daring, dlsb?

**Comment by tuanpembual** [comment]
boleh pak.

**Comment by blu3f4lc0n** [comment]
ini maksudnya Glosarium kah pak ? , saya boleh bantu ?

**Comment by FaiqAminuddin** [comment]
Boleh.

Pada tanggal 14 Okt 2017 19:22, "Yudha Satya Ami Putra" <
notifications@github.com> menulis:

**Comment by blu3f4lc0n** [comment]
oke, saya sikat kalau begitu

2017-10-14 19:27 GMT+07:00 Faiq Aminuddin <notifications@github.com>:

**Comment by blu3f4lc0n** [comment]
sudah saya pull request pak, mohon dicek

**Comment by FaiqAminuddin** [comment]
ok

Pada tanggal 15 Okt 2017 7:59 PM, "Yudha Satya Ami Putra" <
notifications@github.com> menulis:

**Comment by blu3f4lc0n** [comment]
ada lagi yang bisa dibantu pak (kurang 3 pull request lagi :D)

2017-10-15 20:05 GMT+07:00 Faiq Aminuddin <notifications@github.com>:

**Comment by FaiqAminuddin** [comment]
Membuat tautan dari setiap kata (misalnya 'Luring') ke halaman glosarium
bagian kata 'Luring'. Seperti di Wikipedia

Pada tanggal 15 Okt 2017 8:20 PM, "Yudha Satya Ami Putra" <
notifications@github.com> menulis:

**Comment by blu3f4lc0n** [comment]
oh iya pak... boleh

2017-10-16 1:18 GMT+07:00 Faiq Aminuddin <notifications@github.com>:

**Comment by blu3f4lc0n** [comment]
sementara sudah pak, monggo dicek, mungkin ada daftar istilah glosarium, saya bisa bantu bikin merge agar tampil di wiki dev blankon

**Comment by FaiqAminuddin** [comment]
halaman ini bisa digabung dengan glosarium >> https://github.com/BlankOn/wiki/blob/master/TimPengembang/Dokumentasi/Panduan/PanduanWiki/KamusBlankOn.md

**Comment by blu3f4lc0n** [comment]
oh iya , siap, saya sikat lagi kalau gitu

2017-10-20 6:49 GMT+07:00 Faiq Aminuddin <notifications@github.com>:

**Comment by blu3f4lc0n** [comment]
sudah saya komit pak, monggo dicek @FaiqAminuddin

**Comment by FaiqAminuddin** [comment]
Pak @blu3f4lc0n padanan kata pada kamus BlankOn perlu disalin dan ditempel di masing-masing berkas pada /DaftarGlosarium.

Bila ingin melengkapi dengan penjelasan/arti yang lebih detail dapat dicari atau diarahkan ke web kbbi daring https://kbbi.kemdikbud.go.id/ atau https://kbbi.kemdikbud.go.id/entri/...

Padanan kata dengan awalan huruf B sudah saya saltem. Silahkan dilanjutkan sampai Z.

Terima kasih.

**Comment by blu3f4lc0n** [comment]
siap pak, tapi saya kerjakan bukun panduan yang bab 1 dulu ya...

Pada 29 Oktober 2017 02.47, Faiq Aminuddin <notifications@github.com>
menulis:

**Comment by herpiko** [comment]
Dipindahkan ke https://github.com/BlankOn/Verbeek/issues/69
