### ISSUE TITLE
Usulan stuktur wiki yang baru

### ISSUE THREAD

**Issue by herpiko** [BlankOn/wiki#4]
Struktur yang dimaksud di sini adalah struktur direktori di repository-nya. Struktur tautan menyesuaikan. Berikut usulan (urutan tidak penting) :

- assets
  - images (dir)
    - berkas2 gambar
  - berkas2 selain gambar 
  - berkas2 selain gambar
  - dst
- Tim Pengembang
  - Nama tim (`deskripsi, SOP, semua masuk dalam 1 halaman` atau setiap tim punya folder sendiri supaya rapi ?)
  - Nama tim
  - dst
- Rilis Distribusi Linux
  - 1
    - catatan rilis
    - daftar pengembang
    - daftar paket 
    - Spesifikasi
    - Artwork (artwork memiliki struktur sendiri di dev.boi, dengan format `Menuju xxx`, pindah kesini per rilis)
    - dst
  - 2
  - 3
- Blan
  - BlanKoding
    - BlanKoding 01-01-2005 (md)
    - BlanKoding 01-01-2006 (md)
    - dst
  - BlanKopdar
    - BlanKopdar 01-01-2007 (md)
    - dst
  - BlanKonf
    - BlanKonf #1 (md)
    - BlanKonf #2 (md)
- Blank (produk2 ?)
  - BlankOn Linux (dir)
    - README.md
    - Racikan2
    - Halaman2 wiki terkait distro
    - Saya ngebayangin di bawah sini ada kelompok dokumentasi teknis ala archlinux, catatan oprekan, workaround dst
  - BlankBanana (dir)
     - README.md
  - BlankBerry
  - Data.boi
  - Ridon
  - dst
- Tantangan BlankOn
  - tantangan2 lama yang ada di wiki
  - Sayembara2
- Rapat
  - catatan2 rapat
- Proyek
  - Tentang BlankOn
  - Misi BlankOn
  - EtikaMilis
  - FAQ
  - Infrastruktur (dir)
    - Halaman2 infra (banyak banget ini)
    - Daftar mesin
    - dst
  - Riset (dir)
    - xyz
    - dst
  - Humas (dir)
    -  Donasi
    - Halaman2 `Pemasaran`
    - Presentasi2 BlankOn (dir)
       - items di bawah http://dev.blankonlinux.or.id/wiki/Konferensi
       - Pemasaran/PresentasiBlankon
    - Berkas2 proposal
    - Sertifikasi
    - dst

**Comment by FaiqAminuddin** [comment]
Saya setuju tiap tim punya folder

**Comment by trisfaizal** [comment]
ikutan menyesuaikan
