### ISSUE TITLE
Panduan Migrasi Wiki

### ISSUE THREAD

**Issue by herpiko** [BlankOn/wiki#5]
Tentang penamaan folder, nama berkas dan lain2 perlu ditetapkan agar konsisten.

**Comment by herpiko** [comment]
@FaiqAminuddin @tuanpembual Saya usul begini, ngikut format devboi lama

- Baik nama folder maupun nama berkas, pakai pedoman untuk `judul` dalam EYD/PUEBI,yaitu huruf besar di awal kata kecuali untuk partikel, hanya saja spasinya dihilangkan, contoh : 

  - TimPengembang
  - TimDokumentasi.md
  - BlanKonf#1.md
  - EtikaMilis

**Comment by tuanpembual** [comment]
LGTM.
Lanjut eksekusi.
Hirarki legacy sdh rapi pak.

**Comment by herpiko** [comment]
@tuanpembual

Hirarki yang legacy gak rapi dan campur aduk pak, bisa dilihat di http://dev.blankonlinux.or.id/wiki/TitleIndex

Usulan hirarki ada di tiket sebelah

**Comment by herpiko** [comment]
Output tiket ini adalah halaman panduan menyunting wiki, setelah ada PR saya tutup.

**Comment by FaiqAminuddin** [comment]
Setuju

**Comment by FaiqAminuddin** [comment]
Legacy itu yang dimigrasi atau yang ditinggal sich?

**Comment by herpiko** [comment]
legacy == yang lama == yang ada di dev.boi sekarang.

**Comment by FaiqAminuddin** [comment]
https://github.com/BlankOn/wiki/pull/10 Panduan Menulis Wiki
 mohon diperiksa
terima kasih

**Comment by FaiqAminuddin** [comment]
https://github.com/BlankOn/wiki/pull/10 Panduan Menulis Wiki
 mohon diperiksa
terima kasih

**Comment by guspur** [comment]
Mohon bimbingan. untuk menulis markdown aplikasi apa yang bisa kita pakai? 

Terima kasih.

**Comment by FaiqAminuddin** [comment]
Saya pakai haroopad
