### ISSUE TITLE
Fitur pencarian wiki

### ISSUE THREAD

**Issue by herpiko** [BlankOn/wiki#79]

**Comment by FaiqAminuddin** [comment]
Siapa yang bisa bantu?

**Comment by herpiko** [comment]
Sayadong <3

**Comment by FaiqAminuddin** [comment]
makasih

**Comment by samsulmaarif** [comment]
kasih label `Hacktoberfest` :+1:

**Comment by FaiqAminuddin** [comment]
bagaimana kalau pakai ini http://brianrakhmataji.me/blog/programming/membuat-fitur-search- pada-jekyll-dengan-lunr-dot-js/ ?

@herpiko

**Comment by FaiqAminuddin** [comment]
sudah kami coba tapi belum berhasil

**Comment by herpiko** [comment]
Dipindahkan ke https://github.com/BlankOn/Verbeek/issues/70
