### ISSUE TITLE
Usul Daftar Indeks [Urgent]

### ISSUE THREAD

**Issue by tuanpembual** [BlankOn/wiki#8]
Kita butuh daftar isi (title index) untuk mengetahui, halaman apa saja yg sudah ada. sehigga bsa bantu dikit2 koreksi konten.

**Comment by namamu** [comment]
# Rancangan Daftar isi
[Beranda](README.
md)

* Tentang BlankOn
  * Misi

* Pengembang
  * Cara mendaftar sebagai pengembang
  * Dokumentasi
     * Alur Kerja
  * Riset
  * Infrastruktur
  * Humas
   
  ....
Maaf otw dulu

**Comment by FaiqAminuddin** [comment]
Pak manajer Estu ingin Daftar isi yang otomatis atau manual?
Kalau yang otomatis, mungkin teman-teman dari tim infra lebih ahli.

**Comment by herpiko** [comment]
@FaiqAminuddin otomatis itu maksudnya gimana pak?

**Comment by herpiko** [comment]
Kalau struktur di sebelah (https://github.com/BlankOn/wiki/issues/4) pada akur, saya coba bikinin daftar isinya plus tautan ke halamannya masing di dev.boi, jadi tinggal comot2.

**Comment by FaiqAminuddin** [comment]
Otomatis = pakai kode-kode yang bisa menjalankan perintah semacam ls dan ls -tautan.

Kalau di .odt kan ada fasilitas utk buat toc. Mungkin di .md juga ada

**Comment by FaiqAminuddin** [comment]
Daftar isi sudah saya buat. Semoga sesuai harapan.
Untuk indeks saya belum ada ide cara buatnya.
