### ISSUE TITLE
Pindahkan repo BlankOn/Infrastruktur ke wiki

### ISSUE THREAD

**Issue by samsulmaarif** [BlankOn/wiki#80]
List file :
- [x] IRGSH.md #81 
- [ ] Menjalankan Pabrik CD di alynne.md
- [ ] PbuilderBaseTgz.md
- [x] README.md (not migrated)
- [ ] Reprepro.md
- [x] django-fastcgi-nginx.md #81 
- [ ] irgsh-di-rani.md (merged with IRGSH.md) #81 
- [ ] supybot.md
- [ ] tempel-boi.md

**Comment by samsulmaarif** [comment]
belum selesai pak @FaiqAminuddin

**Comment by samsulmaarif** [comment]
centangnya belum dicentang semua... :-D

**Comment by samsulmaarif** [comment]
sekarang sudah

**Comment by herpiko** [comment]
@samsulmaarif repo `blankon/infrastruktur` sudah aman untuk dihapus?

**Comment by samsulmaarif** [comment]
@herpiko aman pak

**Comment by herpiko** [comment]
@samsulmaarif ok saya bantu hapus.
